/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace AthleteID {
  export type ResultViewStruct = {
    resultId: BigNumberish;
    eventId: BigNumberish;
    competitorId: string;
    competitorWallet: AddressLike;
    submitter: AddressLike;
    resultCID: string;
    status: BigNumberish;
    timestamp: BigNumberish;
    confirmCount: BigNumberish;
    encTime: BytesLike;
    encRank: BytesLike;
  };

  export type ResultViewStructOutput = [
    resultId: bigint,
    eventId: bigint,
    competitorId: string,
    competitorWallet: string,
    submitter: string,
    resultCID: string,
    status: bigint,
    timestamp: bigint,
    confirmCount: bigint,
    encTime: string,
    encRank: string
  ] & {
    resultId: bigint;
    eventId: bigint;
    competitorId: string;
    competitorWallet: string;
    submitter: string;
    resultCID: string;
    status: bigint;
    timestamp: bigint;
    confirmCount: bigint;
    encTime: string;
    encRank: string;
  };
}

export interface AthleteIDInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addReferees"
      | "confidentialProtocolId"
      | "createEvent"
      | "disputeResult"
      | "eventsById"
      | "getConfirmCount"
      | "getResult"
      | "getResultsByCompetitor"
      | "getResultsByEvent"
      | "hasSigned"
      | "isRefereeForEvent"
      | "nextEventId"
      | "nextResultId"
      | "refereeCountForEvent"
      | "resolveDispute"
      | "resultEvidence"
      | "resultIdsByCompetitorHash"
      | "resultIdsByEvent"
      | "resultsById"
      | "setEventActive"
      | "setEventThreshold"
      | "signResult"
      | "submitResult"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EventCreated"
      | "EventUpdated"
      | "RefereesAdded"
      | "ResultDisputed"
      | "ResultSigned"
      | "ResultStatusChanged"
      | "ResultSubmitted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addReferees",
    values: [BigNumberish, AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createEvent",
    values: [string, BigNumberish, BigNumberish, BigNumberish, AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "disputeResult",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "eventsById",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getConfirmCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getResult",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getResultsByCompetitor",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getResultsByEvent",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasSigned",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isRefereeForEvent",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nextEventId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextResultId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "refereeCountForEvent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveDispute",
    values: [BigNumberish, boolean, string]
  ): string;
  encodeFunctionData(
    functionFragment: "resultEvidence",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "resultIdsByCompetitorHash",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "resultIdsByEvent",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "resultsById",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setEventActive",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setEventThreshold",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "signResult",
    values: [BigNumberish, boolean, string]
  ): string;
  encodeFunctionData(
    functionFragment: "submitResult",
    values: [
      BigNumberish,
      string,
      AddressLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      string
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "addReferees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createEvent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disputeResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "eventsById", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getConfirmCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getResult", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getResultsByCompetitor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getResultsByEvent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasSigned", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isRefereeForEvent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextEventId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextResultId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "refereeCountForEvent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resultEvidence",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resultIdsByCompetitorHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resultIdsByEvent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resultsById",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setEventActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setEventThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "signResult", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitResult",
    data: BytesLike
  ): Result;
}

export namespace EventCreatedEvent {
  export type InputTuple = [
    eventId: BigNumberish,
    organizer: AddressLike,
    eventCID: string
  ];
  export type OutputTuple = [
    eventId: bigint,
    organizer: string,
    eventCID: string
  ];
  export interface OutputObject {
    eventId: bigint;
    organizer: string;
    eventCID: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EventUpdatedEvent {
  export type InputTuple = [
    eventId: BigNumberish,
    active: boolean,
    threshold: BigNumberish
  ];
  export type OutputTuple = [
    eventId: bigint,
    active: boolean,
    threshold: bigint
  ];
  export interface OutputObject {
    eventId: bigint;
    active: boolean;
    threshold: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefereesAddedEvent {
  export type InputTuple = [eventId: BigNumberish, referees: AddressLike[]];
  export type OutputTuple = [eventId: bigint, referees: string[]];
  export interface OutputObject {
    eventId: bigint;
    referees: string[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResultDisputedEvent {
  export type InputTuple = [
    resultId: BigNumberish,
    challenger: AddressLike,
    disputeCID: string
  ];
  export type OutputTuple = [
    resultId: bigint,
    challenger: string,
    disputeCID: string
  ];
  export interface OutputObject {
    resultId: bigint;
    challenger: string;
    disputeCID: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResultSignedEvent {
  export type InputTuple = [
    resultId: BigNumberish,
    signer: AddressLike,
    approve: boolean,
    evidenceCID: string
  ];
  export type OutputTuple = [
    resultId: bigint,
    signer: string,
    approve: boolean,
    evidenceCID: string
  ];
  export interface OutputObject {
    resultId: bigint;
    signer: string;
    approve: boolean;
    evidenceCID: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResultStatusChangedEvent {
  export type InputTuple = [
    resultId: BigNumberish,
    oldStatus: BigNumberish,
    newStatus: BigNumberish
  ];
  export type OutputTuple = [
    resultId: bigint,
    oldStatus: bigint,
    newStatus: bigint
  ];
  export interface OutputObject {
    resultId: bigint;
    oldStatus: bigint;
    newStatus: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResultSubmittedEvent {
  export type InputTuple = [
    resultId: BigNumberish,
    eventId: BigNumberish,
    competitorId: string,
    submitter: AddressLike,
    resultCID: string
  ];
  export type OutputTuple = [
    resultId: bigint,
    eventId: bigint,
    competitorId: string,
    submitter: string,
    resultCID: string
  ];
  export interface OutputObject {
    resultId: bigint;
    eventId: bigint;
    competitorId: string;
    submitter: string;
    resultCID: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AthleteID extends BaseContract {
  connect(runner?: ContractRunner | null): AthleteID;
  waitForDeployment(): Promise<this>;

  interface: AthleteIDInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addReferees: TypedContractMethod<
    [eventId: BigNumberish, referees: AddressLike[]],
    [void],
    "nonpayable"
  >;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  createEvent: TypedContractMethod<
    [
      eventCID: string,
      startTime: BigNumberish,
      endTime: BigNumberish,
      threshold: BigNumberish,
      referees: AddressLike[]
    ],
    [bigint],
    "nonpayable"
  >;

  disputeResult: TypedContractMethod<
    [resultId: BigNumberish, disputeCID: string],
    [void],
    "nonpayable"
  >;

  eventsById: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, boolean, bigint] & {
        eventId: bigint;
        organizer: string;
        eventCID: string;
        startTime: bigint;
        endTime: bigint;
        active: boolean;
        threshold: bigint;
      }
    ],
    "view"
  >;

  getConfirmCount: TypedContractMethod<
    [resultId: BigNumberish],
    [bigint],
    "view"
  >;

  getResult: TypedContractMethod<
    [resultId: BigNumberish],
    [AthleteID.ResultViewStructOutput],
    "view"
  >;

  getResultsByCompetitor: TypedContractMethod<
    [competitorId: string],
    [bigint[]],
    "view"
  >;

  getResultsByEvent: TypedContractMethod<
    [eventId: BigNumberish, start: BigNumberish, count: BigNumberish],
    [AthleteID.ResultViewStructOutput[]],
    "view"
  >;

  hasSigned: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  isRefereeForEvent: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  nextEventId: TypedContractMethod<[], [bigint], "view">;

  nextResultId: TypedContractMethod<[], [bigint], "view">;

  refereeCountForEvent: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  resolveDispute: TypedContractMethod<
    [resultId: BigNumberish, uphold: boolean, arg2: string],
    [void],
    "nonpayable"
  >;

  resultEvidence: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;

  resultIdsByCompetitorHash: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  resultIdsByEvent: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  resultsById: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        string
      ] & {
        resultId: bigint;
        eventId: bigint;
        competitorId: string;
        competitorWallet: string;
        submitter: string;
        resultCID: string;
        status: bigint;
        timestamp: bigint;
        confirmCount: bigint;
        encTime: string;
        encRank: string;
      }
    ],
    "view"
  >;

  setEventActive: TypedContractMethod<
    [eventId: BigNumberish, active: boolean],
    [void],
    "nonpayable"
  >;

  setEventThreshold: TypedContractMethod<
    [eventId: BigNumberish, threshold: BigNumberish],
    [void],
    "nonpayable"
  >;

  signResult: TypedContractMethod<
    [resultId: BigNumberish, approve: boolean, evidenceCID: string],
    [void],
    "nonpayable"
  >;

  submitResult: TypedContractMethod<
    [
      eventId: BigNumberish,
      competitorId: string,
      competitorWallet: AddressLike,
      encTimeExt: BytesLike,
      proofTime: BytesLike,
      encRankExt: BytesLike,
      proofRank: BytesLike,
      resultCID: string
    ],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addReferees"
  ): TypedContractMethod<
    [eventId: BigNumberish, referees: AddressLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createEvent"
  ): TypedContractMethod<
    [
      eventCID: string,
      startTime: BigNumberish,
      endTime: BigNumberish,
      threshold: BigNumberish,
      referees: AddressLike[]
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "disputeResult"
  ): TypedContractMethod<
    [resultId: BigNumberish, disputeCID: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "eventsById"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, boolean, bigint] & {
        eventId: bigint;
        organizer: string;
        eventCID: string;
        startTime: bigint;
        endTime: bigint;
        active: boolean;
        threshold: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getConfirmCount"
  ): TypedContractMethod<[resultId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getResult"
  ): TypedContractMethod<
    [resultId: BigNumberish],
    [AthleteID.ResultViewStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getResultsByCompetitor"
  ): TypedContractMethod<[competitorId: string], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getResultsByEvent"
  ): TypedContractMethod<
    [eventId: BigNumberish, start: BigNumberish, count: BigNumberish],
    [AthleteID.ResultViewStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasSigned"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isRefereeForEvent"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextEventId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextResultId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "refereeCountForEvent"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "resolveDispute"
  ): TypedContractMethod<
    [resultId: BigNumberish, uphold: boolean, arg2: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "resultEvidence"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "resultIdsByCompetitorHash"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "resultIdsByEvent"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "resultsById"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        string
      ] & {
        resultId: bigint;
        eventId: bigint;
        competitorId: string;
        competitorWallet: string;
        submitter: string;
        resultCID: string;
        status: bigint;
        timestamp: bigint;
        confirmCount: bigint;
        encTime: string;
        encRank: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "setEventActive"
  ): TypedContractMethod<
    [eventId: BigNumberish, active: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setEventThreshold"
  ): TypedContractMethod<
    [eventId: BigNumberish, threshold: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "signResult"
  ): TypedContractMethod<
    [resultId: BigNumberish, approve: boolean, evidenceCID: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitResult"
  ): TypedContractMethod<
    [
      eventId: BigNumberish,
      competitorId: string,
      competitorWallet: AddressLike,
      encTimeExt: BytesLike,
      proofTime: BytesLike,
      encRankExt: BytesLike,
      proofRank: BytesLike,
      resultCID: string
    ],
    [bigint],
    "nonpayable"
  >;

  getEvent(
    key: "EventCreated"
  ): TypedContractEvent<
    EventCreatedEvent.InputTuple,
    EventCreatedEvent.OutputTuple,
    EventCreatedEvent.OutputObject
  >;
  getEvent(
    key: "EventUpdated"
  ): TypedContractEvent<
    EventUpdatedEvent.InputTuple,
    EventUpdatedEvent.OutputTuple,
    EventUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RefereesAdded"
  ): TypedContractEvent<
    RefereesAddedEvent.InputTuple,
    RefereesAddedEvent.OutputTuple,
    RefereesAddedEvent.OutputObject
  >;
  getEvent(
    key: "ResultDisputed"
  ): TypedContractEvent<
    ResultDisputedEvent.InputTuple,
    ResultDisputedEvent.OutputTuple,
    ResultDisputedEvent.OutputObject
  >;
  getEvent(
    key: "ResultSigned"
  ): TypedContractEvent<
    ResultSignedEvent.InputTuple,
    ResultSignedEvent.OutputTuple,
    ResultSignedEvent.OutputObject
  >;
  getEvent(
    key: "ResultStatusChanged"
  ): TypedContractEvent<
    ResultStatusChangedEvent.InputTuple,
    ResultStatusChangedEvent.OutputTuple,
    ResultStatusChangedEvent.OutputObject
  >;
  getEvent(
    key: "ResultSubmitted"
  ): TypedContractEvent<
    ResultSubmittedEvent.InputTuple,
    ResultSubmittedEvent.OutputTuple,
    ResultSubmittedEvent.OutputObject
  >;

  filters: {
    "EventCreated(uint256,address,string)": TypedContractEvent<
      EventCreatedEvent.InputTuple,
      EventCreatedEvent.OutputTuple,
      EventCreatedEvent.OutputObject
    >;
    EventCreated: TypedContractEvent<
      EventCreatedEvent.InputTuple,
      EventCreatedEvent.OutputTuple,
      EventCreatedEvent.OutputObject
    >;

    "EventUpdated(uint256,bool,uint8)": TypedContractEvent<
      EventUpdatedEvent.InputTuple,
      EventUpdatedEvent.OutputTuple,
      EventUpdatedEvent.OutputObject
    >;
    EventUpdated: TypedContractEvent<
      EventUpdatedEvent.InputTuple,
      EventUpdatedEvent.OutputTuple,
      EventUpdatedEvent.OutputObject
    >;

    "RefereesAdded(uint256,address[])": TypedContractEvent<
      RefereesAddedEvent.InputTuple,
      RefereesAddedEvent.OutputTuple,
      RefereesAddedEvent.OutputObject
    >;
    RefereesAdded: TypedContractEvent<
      RefereesAddedEvent.InputTuple,
      RefereesAddedEvent.OutputTuple,
      RefereesAddedEvent.OutputObject
    >;

    "ResultDisputed(uint256,address,string)": TypedContractEvent<
      ResultDisputedEvent.InputTuple,
      ResultDisputedEvent.OutputTuple,
      ResultDisputedEvent.OutputObject
    >;
    ResultDisputed: TypedContractEvent<
      ResultDisputedEvent.InputTuple,
      ResultDisputedEvent.OutputTuple,
      ResultDisputedEvent.OutputObject
    >;

    "ResultSigned(uint256,address,bool,string)": TypedContractEvent<
      ResultSignedEvent.InputTuple,
      ResultSignedEvent.OutputTuple,
      ResultSignedEvent.OutputObject
    >;
    ResultSigned: TypedContractEvent<
      ResultSignedEvent.InputTuple,
      ResultSignedEvent.OutputTuple,
      ResultSignedEvent.OutputObject
    >;

    "ResultStatusChanged(uint256,uint8,uint8)": TypedContractEvent<
      ResultStatusChangedEvent.InputTuple,
      ResultStatusChangedEvent.OutputTuple,
      ResultStatusChangedEvent.OutputObject
    >;
    ResultStatusChanged: TypedContractEvent<
      ResultStatusChangedEvent.InputTuple,
      ResultStatusChangedEvent.OutputTuple,
      ResultStatusChangedEvent.OutputObject
    >;

    "ResultSubmitted(uint256,uint256,string,address,string)": TypedContractEvent<
      ResultSubmittedEvent.InputTuple,
      ResultSubmittedEvent.OutputTuple,
      ResultSubmittedEvent.OutputObject
    >;
    ResultSubmitted: TypedContractEvent<
      ResultSubmittedEvent.InputTuple,
      ResultSubmittedEvent.OutputTuple,
      ResultSubmittedEvent.OutputObject
    >;
  };
}
