/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AthleteCertificate } from "./AthleteCertificate";
export type { AthleteID } from "./AthleteID";
