/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AthleteCertificate__factory } from "./AthleteCertificate__factory";
export { AthleteID__factory } from "./AthleteID__factory";
